# Generated by Django 6.0.2 on 2026-06-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_course_alter_payment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
